const path = require('path');

module.exports = {
  apps: [
    {
      name: 'scout-reddit-worker',
      cwd: path.resolve(__dirname, 'core'),
      script: './node_modules/tsx/dist/cli.mjs',
      args: 'src/runners/scoutRedditDaemon.ts',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'production',
        PLAYWRIGHT_HEADLESS: 'true',
      },
      error_file: path.resolve(__dirname, 'logs/pm2-scout-reddit.err.log'),
      out_file: path.resolve(__dirname, 'logs/pm2-scout-reddit.out.log'),
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 5000,
      kill_timeout: 5000,
    },
    {
      name: 'reddit-session-watchdog',
      cwd: path.resolve(__dirname, 'core'),
      script: './node_modules/tsx/dist/cli.mjs',
      args: 'src/scripts/redditSessionWatchdog.ts',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '150M',
      env: {
        NODE_ENV: 'production',
      },
      error_file: path.resolve(__dirname, 'logs/pm2-reddit-watchdog.err.log'),
      out_file: path.resolve(__dirname, 'logs/pm2-reddit-watchdog.out.log'),
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 5000,
      kill_timeout: 5000,
    },
  ],
};
